export type BootLineKind = 'kernel' | 'info' | 'ok' | 'fail' | 'target' | 'redacted' | 'prompt'

export interface BootLine {
  text: string
  kind: BootLineKind
}

export const BOOT_LINES: BootLine[] = [
  { kind: 'kernel', text: 'SeaBIOS (version 1.16.3-scp)' },
  { kind: 'kernel', text: 'Booting from Hard Disk...' },
  { kind: 'kernel', text: 'GRUB Loading stage1.5.' },
  { kind: 'kernel', text: 'GRUB Loading Linux 6.8.0-scp ...' },
  { kind: 'redacted', text: '███-█████ containment firmware revision ██.██.█' },
  { kind: 'kernel', text: 'Linux version 6.8.0-scp (build@localhost) #1 SMP xterm.js 1.0.0' },
  { kind: 'kernel', text: 'Command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-scp root=/dev/vda1 ro quiet' },
  { kind: 'kernel', text: 'KERNEL supported cpus:  Intel 80386, AMD K7/K8, ARM64, RISC-V' },
  { kind: 'kernel', text: 'Memory: 1024MB available, 896MB physical RAM' },
  { kind: 'kernel', text: 'Kernel command line: root=/dev/vda1 ro ████████' },
  { kind: 'kernel', text: 'ACPI: RSDP 0x00000000000F0000, RSDT 0x00000000000F0010' },
  { kind: 'kernel', text: 'ACPI: Interpreter enabled, tables loaded, ACPI BIOS IRQ0 mode' },
  { kind: 'kernel', text: 'pci 0000:00:00.0: [8086:1237] type 00 class 0x060000' },
  { kind: 'kernel', text: 'pci 0000:00:01.0: [8086:7000] type 01 class 0x060100' },
  { kind: 'redacted', text: 'SECURE BOOT: signature check for ████████ passed' },
  { kind: 'kernel', text: 'PCI-DMA: Using software bounce buffering for IO (SWIOTLB)' },
  { kind: 'kernel', text: 'virtio_blk virtio0: [vda] 4194304 512-byte logical blocks (2.1 GB)' },
  { kind: 'kernel', text: 'virtio_net virtio1: Features available: +ctrl_vq +event_idx' },
  { kind: 'kernel', text: 'e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 52:54:00:12:34:56' },
  { kind: 'kernel', text: 'input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input0' },
  { kind: 'kernel', text: 'Console: switching to colour frame buffer device 128x40' },
  { kind: 'kernel', text: 'Detected virtualization: browser sandbox' },
  { kind: 'kernel', text: 'Freeing unused kernel image (initmem) memory: 2040K' },
  { kind: 'redacted', text: '█-██ containment cell integrity check: ████████' },
  { kind: 'info', text: 'Mounting proc on /proc ...' },
  { kind: 'info', text: 'Mounting sysfs on /sys ...' },
  { kind: 'info', text: 'Mounting devtmpfs on /dev ...' },
  { kind: 'info', text: 'Mounting tmpfs on /tmp ...' },
  { kind: 'info', text: 'Mounting cgroup2 on /sys/fs/cgroup ...' },
  { kind: 'redacted', text: 'Mounting ████████ on /████ ...' },
  { kind: 'info', text: 'Running /dev/vda1: fsck.ext4 ...' },
  { kind: 'ok', text: '/dev/vda1: clean, 5120/131072 files, 40960/524288 blocks' },
  { kind: 'redacted', text: 'Scanning for anomalous artifacts in /dev ... none found' },
  { kind: 'info', text: 'Purging expired containment records ...' },
  { kind: 'redacted', text: '[DATA EXPUNGED] 37 records removed' },
  { kind: 'info', text: 'Wiping decommissioned ████████ memory segments ...' },
  { kind: 'redacted', text: 'Deleted ██████████ (classified)' },
  { kind: 'info', text: 'Vacuuming stale journal entries older than 30 days ...' },
  { kind: 'ok', text: 'Removed 184 journal entries (2.3 MB).' },
  { kind: 'info', text: 'Running tmpfiles.d cleanup for /tmp ...' },
  { kind: 'ok', text: 'Removed 12 stale temporary files.' },
  { kind: 'info', text: 'Clearing obsolete kernel module cache ...' },
  { kind: 'ok', text: 'Deleted 37 cached module files.' },
  { kind: 'info', text: 'Remounting /dev/vda1 read-write ...' },
  { kind: 'ok', text: 'Remounted /dev/vda1 read-write.' },
  { kind: 'ok', text: 'Started Journal Service.' },
  { kind: 'ok', text: 'Started udev Kernel Device Manager.' },
  { kind: 'ok', text: 'Started udev Coldplug all Devices.' },
  { kind: 'ok', text: 'Reached target Local File Systems (Pre).' },
  { kind: 'ok', text: 'Started File System Check on Root Device.' },
  { kind: 'ok', text: 'Started File System Check Daemon.' },
  { kind: 'ok', text: 'Started D-Bus System Message Bus.' },
  { kind: 'ok', text: 'Started System Logging Service (rsyslogd).' },
  { kind: 'ok', text: 'Started cron daemon.' },
  { kind: 'redacted', text: 'Started ███ containment unit ██████-█.' },
  { kind: 'redacted', text: 'Site-██ security subsystem online.' },
  { kind: 'info', text: 'Starting Network Manager ...' },
  { kind: 'fail', text: 'Failed to start Network Manager.' },
  { kind: 'info', text: 'Retrying network service start (attempt 2/3) ...' },
  { kind: 'ok', text: 'Started Network Manager.' },
  { kind: 'info', text: 'Configuring eth0 with DHCP ...' },
  { kind: 'ok', text: 'eth0: acquired lease 192.168.1.100, lease time 86400' },
  { kind: 'info', text: 'Starting avahi daemon ...' },
  { kind: 'fail', text: 'Failed to start avahi-daemon.service.' },
  { kind: 'info', text: 'Restarting avahi daemon ...' },
  { kind: 'ok', text: 'Started Avahi mDNS/DNS-SD Stack.' },
  { kind: 'target', text: 'Reached target Network is Online.' },
  { kind: 'redacted', text: 'Establishing secure uplink to ██████████ ...' },
  { kind: 'ok', text: 'Uplink ██████████ established.' },
  { kind: 'info', text: 'Setting system time to 2026-08-07 02:00:00 UTC ...' },
  { kind: 'ok', text: 'Synchronized system clock to hardware clock.' },
  { kind: 'info', text: 'Starting User Manager for user (uid=1000) ...' },
  { kind: 'ok', text: 'Started User Manager for user (uid=1000).' },
  { kind: 'redacted', text: 'Running personnel clearance sweep ...' },
  { kind: 'ok', text: 'Clearance sweep passed.' },
  { kind: 'info', text: 'Starting login service on tty1 ...' },
  { kind: 'ok', text: 'Started Login Service.' },
  { kind: 'target', text: 'Reached target Multi-User System.' },
  { kind: 'target', text: 'Reached target Graphical Interface.' },
  { kind: 'info', text: 'Initializing SCP Terminal kernel module ...' },
  { kind: 'ok', text: 'SCP Terminal module loaded.' },
  { kind: 'info', text: 'Initializing OPFS storage backend ...' },
  { kind: 'ok', text: 'OPFS storage backend ready.' },
  { kind: 'info', text: 'Registering virtual file system root ...' },
  { kind: 'ok', text: 'Virtual file system mounted at /.' },
  { kind: 'prompt', text: 'login: ' },
]

export function findFailures(): BootLine[] {
  return BOOT_LINES.filter((line) => line.kind === 'fail')
}
